{
 "title": "Proto 1",
 "time": { "from": "2019-04-02T10:54:03.385Z", "to": "2019-04-02T11:02:17.993Z" },
 "panels": [
  {
   "title": "Total ACK messages consumed by Producer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ack_consumer_number_messages_total"
    }
   ]
  },
  {
   "title": "Total Messages dequeue by Consumers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consumer_number_messages_total" }
   ]
  },
  {
   "title": "Number of batches generated by Producer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "batch_batches_total" }
   ]
  },
  {
   "title": "Process CPU Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(process_cpu_usage) by (instance, Id)"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes) by (instance, id)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_states_threads" }
   ]
  }
 ]
}