apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-svc
spec:
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: grafana-dp