---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka-svc
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka-dp
    id: "1"