---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  labels:
    app: node-exporter-svc
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app: node-exporter-dp