---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: node-exporter-deployment
spec:
  template:
    metadata:
      labels:
        app: node-exporter-dp
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:latest
          ports:
            - containerPort: 9100