---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  labels:
    app: producer-svc
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app: producer-dp