---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: prom-deployment-1
spec:
  template:
    metadata:
      labels:
        app: prometheus-dp
    spec:
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus:latest
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: config-volume
          configMap:
            name: prom-config-map