apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    name: prometheus-svc
    kubernetes.io/name: "Prometheus"
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus-dp
