---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-deployment
spec:
  template:
    metadata:
      labels:
        app: zookeeper-dp
    spec:
      containers:
        - name: zoo1
          image: zookeeper:3.4.9
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: zoo1