version: "3.3"

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zoo1/data:/data
      - ./zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.1.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://192.168.99.101:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: topicTest2:3:1
    depends_on:
      - zoo1

  producer1:
    image: adolfoecs/producer:latest6
    hostname: producer1
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKER: "kafka1:9092"
      PROTO_1_TOPIC: "topicTest2"
    depends_on:
      - kafka1

  consumer1:
    image: adolfoecs/consumer:latest6
    hostname: consumer1
    ports:
      - "8090:8090"
    environment:
      KAFKA_BROKER: "kafka1:9092"
      PORT: "8090"
      PROTO_1_TOPIC: "topicTest2"
    depends_on:
      - kafka1

  consumer2:
    image: adolfoecs/consumer:latest6
    hostname: consumer2
    ports:
      - "8091:8091"
    environment:
      KAFKA_BROKER: "kafka1:9092"
      PORT: "8091"
      PROTO_1_TOPIC: "topicTest2"
    depends_on:
      - kafka1

  consumer3:
    image: adolfoecs/consumer:latest6
    hostname: consumer3
    ports:
      - "8092:8092"
    environment:
      KAFKA_BROKER: "kafka1:9092"
      PORT: "8092"
      PROTO_1_TOPIC: "topicTest2"
    depends_on:
      - kafka1