{
 "title": "Proto 1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total ACK messages consumed by Producer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ack_consumer_number_messages_total"
    }
   ]
  },
  {
   "title": "Total Messages dequeue by Consumers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consumer_number_messages_total" }
   ]
  },
  {
   "title": "Number of batches generated by Producer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "batch_batches_total" }
   ]
  },
  {
   "title": "Process CPU Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  }
 ]
}