version: "3.3"

services:
  producer1:
    image: adolfoecs/producer:latest
    hostname: producer1
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKER: "kafka1:9092"
      CONSUMER_TOPIC: "${CONSUMER_TOPIC}"
      ACK_CONSUMER_CLIENT_ID: "${ACK_CONSUMER_CLIENT_ID}"
      ACK_CONSUMER_TOPIC: "${ACK_CONSUMER_TOPIC}"
    depends_on:
      - kafka1

  consumer1:
    image: adolfoecs/consumer:latest
    hostname: consumer1
    ports:
      - "8090:8090"
    environment:
      KAFKA_BROKER: "kafka1:9092"
      PORT: "8090"
      CONSUMER_TOPIC: "${CONSUMER_TOPIC}"
      ACK_CONSUMER_CLIENT_ID: "${ACK_CONSUMER_CLIENT_ID}_1"
      ACK_CONSUMER_TOPIC: "${ACK_CONSUMER_TOPIC}"
    depends_on:
      - kafka1

  consumer2:
    image: adolfoecs/consumer:latest
    hostname: consumer2
    ports:
      - "8091:8091"
    environment:
      KAFKA_BROKER: "kafka1:9092"
      PORT: "8091"
      CONSUMER_TOPIC: "${CONSUMER_TOPIC}"
      ACK_CONSUMER_CLIENT_ID: "${ACK_CONSUMER_CLIENT_ID}_2"
      ACK_CONSUMER_TOPIC: "${ACK_CONSUMER_TOPIC}"
    depends_on:
      - kafka1

  consumer3:
    image: adolfoecs/consumer:latest
    hostname: consumer3
    ports:
      - "8092:8092"
    environment:
      KAFKA_BROKER: "kafka1:9092"
      PORT: "8092"
      CONSUMER_TOPIC: "${CONSUMER_TOPIC}"
      ACK_CONSUMER_CLIENT_ID: "${ACK_CONSUMER_CLIENT_ID}_3"
      ACK_CONSUMER_TOPIC: "${ACK_CONSUMER_TOPIC}"
    depends_on:
      - kafka1